import {
  celogo,
  certificate1,
  certDevrel,
  certSolidity,
  certWebdev,
  certCampbuidl,
  certCcip,
  certChainlinkFunctions,
  devrellogo,
  devrelResourcesHubShot,
  filecoin,
  hardhat,
  langchain,
  langgraph,
  queenCitySoundboardShot,
  wayalabslogo,
} from "../assets";
import {
  SiCss3,
  SiDocker,
  SiExpress,
  SiFigma,
  SiFlask,
  SiFramer,
  SiGit,
  SiHtml5,
  SiJavascript,
  SiMongodb,
  SiNodedotjs,
  SiNextdotjs,
  SiOpenai,
  SiPostgresql,
  SiPython,
  SiReact,
  SiRedis,
  SiRedux,
  SiSocketdotio,
  SiSolidity,
  SiSupabase,
  SiTailwindcss,
  SiThreedotjs,
  SiTypescript,
  SiVercel,
  SiVite,
  SiFastapi,
  SiEthereum,
  SiIpfs,
} from "react-icons/si/index.js";

const SHOT = (url) =>
  `https://image.thum.io/get/width/1280/crop/800/noanimate/${url}`;

export const navLinks = [
  { id: "project", title: "Projects" },
  { id: "experience", title: "Experience" },
  { id: "play", title: "Playground" },
];

const technologies = [
  { name: "Python", icon: SiPython },
  { name: "TypeScript", icon: SiTypescript },
  { name: "JavaScript", icon: SiJavascript },
  { name: "Solidity", icon: SiSolidity },
  { name: "HTML5", icon: SiHtml5 },
  { name: "CSS3", icon: SiCss3 },
  { name: "React", icon: SiReact },
  { name: "Next.js", icon: SiNextdotjs },
  { name: "Vite", icon: SiVite },
  { name: "Tailwind CSS", icon: SiTailwindcss },
  { name: "Framer Motion", icon: SiFramer },
  { name: "Redux", icon: SiRedux },
  { name: "Node.js", icon: SiNodedotjs },
  { name: "Express", icon: SiExpress },
  { name: "Flask", icon: SiFlask },
  { name: "FastAPI", icon: SiFastapi },
  { name: "OpenAI", icon: SiOpenai },
  { name: "Socket.IO", icon: SiSocketdotio },
  { name: "Ethereum", icon: SiEthereum },
  { name: "IPFS", icon: SiIpfs },
  { name: "Supabase", icon: SiSupabase },
  { name: "PostgreSQL", icon: SiPostgresql },
  { name: "MongoDB", icon: SiMongodb },
  { name: "Redis", icon: SiRedis },
  { name: "Docker", icon: SiDocker },
  { name: "Git", icon: SiGit },
  { name: "Vercel", icon: SiVercel },
  { name: "Figma", icon: SiFigma },
  { name: "Three.js", icon: SiThreedotjs },
  { name: "LangGraph", iconSrc: langgraph },
  { name: "LangChain", iconSrc: langchain },
  { name: "Ethers.js", icon: SiEthereum },
  { name: "Hardhat", iconSrc: hardhat },
  { name: "Filecoin", iconSrc: filecoin },
];

const experiences = [];

export const experiences1 = [
  {
    id: 0,
    img: celogo,
    logoTransform: "scale(1.71)",
    role: "General Manager",
    company: "C&E Granite",
    date: "Nov 2024 – Jan 2026",
    desc: "Led operations and team management at full-service granite/countertop company. Oversaw granite craftsmanship, interior design coordination, customer relations, and on-site project execution across multiple customer engagements.",
    skills: ["Granite craftsmanship", "Interior Design", "Project Management", "Team Leadership", "Customer Relations"],
  },
  {
    id: 1,
    img: wayalabslogo,
    logoTransform: "scale(1.55)",
    role: "Founder & Lead AI Architect",
    company: "wayalabs · OpenJaw",
    date: "May 2021 – Present",
    desc: "Architected and deployed OpenJaw, a hybrid platform combining OpenClaw autonomous agent capabilities with a LangGraph executive multi-agent orchestrator. Built a CEO/CTO/CFO hierarchy with 16 agents, real-time SocketIO dashboard, artifact pipeline, and Telegram integration for strategic coordination across domain directors and execution specialists.",
    skills: ["LangGraph", "LangChain", "Python", "OpenAI", "SocketIO", "Flask", "Autonomous Agents", "Multi-Agent AI"],
  },
  {
    id: 2,
    img: devrellogo,
    logoTransform: "scale(1.6)",
    role: "Resource captain",
    company: "DevRel Uni",
    date: "Jun 2023 – Present",
    desc: "Captain program lead for DevRel Uni community initiative. Coordinated bootcamp resources, mentored developers in open-source contribution, and facilitated community knowledge sharing. Involved in ETHDenver Camp BUIDL and ETHGlobal hackathons.",
    skills: ["Developer Relations", "Community Building", "Web3", "Solidity", "Open Source", "Mentorship"],
  },
  {
    id: 3,
    img: "https://avatars.githubusercontent.com/u/136913552?v=4",
    role: "Managing Owner",
    company: "urban stone collective",
    date: "Feb 2014 – Nov 2024",
    desc: "Owner and operator of full-service architectural countertop and interior design company serving OH/KY/IN markets. Managed granite sourcing, custom fabrication, installation projects, customer design consultations, and team operations across multiple locations.",
    skills: ["Social Entrepreneurship", "Granite craftsmanship", "Project Management", "Interior Design", "Business Operations"],
  },
  {
    id: 4,
    img: "https://avatars.githubusercontent.com/u/136913552?v=4",
    role: "Open Source Contributor",
    company: "Personal Projects · Github",
    date: "Jan 2019 – Aug 2023",
    desc: "Active contributor to open-source software projects on GitHub. Developed and maintained several public repositories spanning Web3, DeFi protocols, and full-stack web applications. Demonstrated best practices in code quality, documentation, and community engagement.",
    skills: ["JavaScript", "Git", "Web3", "Open Source", "Repository Management"],
  },
  {
    id: 5,
    img: "https://avatars.githubusercontent.com/u/136913552?v=4",
    role: "crypto ecosystems advisor",
    company: "estudios amazonia",
    date: "Jan 2019 – Nov 2021",
    desc: "Advised on blockchain technology integration and digital ecosystem design. Specialized in ERC20/BEP20 smart contract standards and DeFi protocol design. Also contributed to film production and media management projects.",
    skills: ["Solidity", "ERC20", "BEP20", "DeFi", "Blockchain", "Digital Ecosystems", "Film Production"],
  },
  {
    id: 6,
    img: "https://avatars.githubusercontent.com/u/136913552?v=4",
    role: "Connectivity Director",
    company: "medrategas",
    date: "Jan 2017 – Jan 2021",
    desc: "Directed connectivity and community outreach initiatives. Managed stakeholder relationships, coordinated cross-functional projects, and fostered partnerships with external organizations to drive business growth.",
    skills: ["Strategic Partnerships", "Community Outreach", "Project Coordination", "Stakeholder Management"],
  },
  {
    id: 7,
    img: "https://avatars.githubusercontent.com/u/136913552?v=4",
    role: "Communications Coordinator",
    company: "Venezuela Information Office",
    date: "Mar 2005 – Apr 2006",
    desc: "Coordinated communications and grassroots organizing for the Venezuela Information Office. Managed media analysis, developed public relations strategies, and organized community engagement events across the Washington DC-Baltimore area.",
    skills: ["Communications", "Media Analysis", "Grassroots Organizing", "Public Relations", "Community Outreach"],
  },
  {
    id: 8,
    img: "https://avatars.githubusercontent.com/u/136913552?v=4",
    role: "Simultaneous Interpreter",
    company: "Affordable Language Services",
    date: "Feb 2003 – Mar 2005",
    desc: "Provided professional simultaneous interpretation services in legal, medical, and social service settings. Facilitated accurate communication and cultural understanding in complex, high-stakes environments requiring precision and cultural sensitivity.",
    skills: ["Spanish Translation", "Legal Interpretation", "Medical Interpretation", "Simultaneous Interpretation"],
  },
  {
    id: 9,
    img: "https://cdn.worldvectorlogo.com/logos/delta-air-lines.svg",
    role: "Sales Specialist",
    company: "Delta Air Lines",
    date: "Aug 1997 – Jun 2002",
    desc: "Managed customer sales and service operations in a fast-paced airline environment. Handled customer inquiries, processed reservations, and achieved sales targets. Developed strong communication and customer service skills in a high-volume setting.",
    skills: ["Customer Service", "Sales", "Customer Relations", "Spanish Language"],
  },
];

const testimonials = [
  {
    project: "AI Agent Architecture",
    testimonial: "https://opengraph.githubassets.com/1/0xwaya/ceo-agent-system",
    name: "Edward Mercado",
    designation: "0xwaya - CEO Agent System",
    company: "16-agent LangGraph hierarchy with CEO/CTO/CFO layer, 6 domain directors, and 7 execution specialists.",
    image: "https://avatars.githubusercontent.com/u/136913552?v=4",
    source_code_link: "https://github.com/0xwaya/ceo-agent-system",
  },
  {
    project: "Web3 & NFT Development",
    testimonial: certificate1,
    name: "Edward Mercado",
    designation: "0xwaya - Loro Dapp / Pandemonium Squad",
    company: "Macaw NFT collection with trait-layer generation, rarity engine, wallet-connected minting on Polygon testnet.",
    image: "https://avatars.githubusercontent.com/u/136913552?v=4",
    source_code_link: "https://github.com/0xwaya/loro-app",
  },
];

export const certificates = [
  {
    project: "Chainlink CCIP",
    image: certCcip,
    name: "Chainlink",
    designation: "Cross-Chain Interoperability Protocol",
    company: "Certified in building cross-chain applications using Chainlink CCIP for secure token and message transfers.",
    source_code_link: "https://github.com/0xwaya",
  },
  {
    project: "Chainlink Functions",
    image: certChainlinkFunctions,
    name: "Chainlink",
    designation: "Chainlink Functions Developer",
    company: "Certified to build hybrid smart contracts using Chainlink Functions for off-chain compute and API access.",
    source_code_link: "https://github.com/0xwaya",
  },
  {
    project: "Camp BUIDL",
    image: certCampbuidl,
    name: "Bufficorn Ventures / ETHDenver",
    designation: "Web3 Bootcamp Graduate",
    company: "Completed ETHDenver Camp BUIDL: Solidity, DeFi, NFTs, and hackathon project delivery.",
    source_code_link: "https://github.com/0xwaya/bufficorn.bootcamp",
  },
  {
    project: "Solidity Development",
    image: certSolidity,
    name: "Alchemy University",
    designation: "Smart Contract Developer",
    company: "Certified in Solidity smart contract development: ERC standards, security patterns, and on-chain testing.",
    source_code_link: "https://github.com/0xwaya",
  },
  {
    project: "Developer Relations",
    image: certDevrel,
    name: "DevRel Uni",
    designation: "DevRel Certification",
    company: "Completed DevRel Uni program covering community building, technical writing, and developer advocacy.",
    source_code_link: "https://dru-resources.vercel.app",
  },
  {
    project: "Web Development",
    image: certWebdev,
    name: "freeCodeCamp",
    designation: "Full Stack Web Developer",
    company: "Certified in responsive web design, JavaScript algorithms, front-end libraries, and APIs.",
    source_code_link: "https://github.com/0xwaya",
  },
  {
    project: "Blockchain Fundamentals",
    image: certificate1,
    name: "Alchemy",
    designation: "Blockchain Developer",
    company: "Foundational certification in blockchain protocols, cryptography, consensus mechanisms, and Web3 tooling.",
    source_code_link: "https://github.com/0xwaya",
  },
];

export const projects = [
  {
    id: 0,
    name: "CEO Agent System",
    description:
      "16-agent LangGraph AI hierarchy with CEO/CTO/CFO layer, 6 domain directors, and 7 execution specialists. Real-time SocketIO dashboard, artifact pipeline, and autonomous task execution.",
    tags: [
      { name: "LangGraph", color: "blue-text-gradient" },
      { name: "Python", color: "green-text-gradient" },
      { name: "Multi-Agent AI", color: "pink-text-gradient" },
    ],
    image: SHOT("https://wayalabs.com"),
    image2: "https://wayalabs.com",
    source_code_link: "https://github.com/0xwaya/ceo-agent-system",
  },
  {
    id: 1,
    name: "QueenCity Soundboard",
    description:
      "Mobile-first event platform connecting Venezuelan artists with Midwest audiences. Next.js + Supabase + Ticket Tailor with full ticketing and RSVP flow.",
    tags: [
      { name: "Next.js", color: "blue-text-gradient" },
      { name: "Supabase", color: "green-text-gradient" },
      { name: "TypeScript", color: "pink-text-gradient" },
    ],
    image: queenCitySoundboardShot,
    image2: "https://queencitysoundboard.com",
    source_code_link: "https://github.com/0xwaya/queencity-soundboard",
  },
  {
    id: 2,
    name: "UrbanStone / Amazon Granite",
    description:
      "Rebrand site for Amazon Granite at urbanstone.co. Supplier scraper prototype for automated product catalog updates. Deployed via Vercel.",
    tags: [
      { name: "React", color: "blue-text-gradient" },
      { name: "Python", color: "green-text-gradient" },
      { name: "Vercel", color: "pink-text-gradient" },
    ],
    image: SHOT("https://urbanstone.co"),
    image2: "https://urbanstone.co",
    source_code_link: "https://github.com/0xwaya/amazon-granite",
  },
  {
    id: 3,
    name: "RadarTV",
    description:
      "Consolidating personal brand with media entity. Modern tech stack for high-performance streaming and community engagement.",
    tags: [
      { name: "React", color: "blue-text-gradient" },
      { name: "Next.js", color: "green-text-gradient" },
      { name: "TailwindCSS", color: "pink-text-gradient" },
    ],
    image: SHOT("https://radartv.vercel.app"),
    image2: "https://radartv.vercel.app",
    source_code_link: "https://github.com/0xwaya/radartv",
  },
  {
    id: 4,
    name: "Loro App / Pandemonium Squad NFT",
    description:
      "Macaw NFT collection Dapp. Beta v0.1 testnet with trait-layer generation, rarity engine, and wallet-connected minting.",
    tags: [
      { name: "Solidity", color: "blue-text-gradient" },
      { name: "React.js", color: "green-text-gradient" },
      { name: "Ethers.js", color: "pink-text-gradient" },
    ],
    image: SHOT("https://loro.vercel.app"),
    image2: "https://loro.vercel.app",
    source_code_link: "https://github.com/0xwaya/loro-app",
  },
  {
    id: 5,
    name: "DreamCar",
    description:
      "Interactive 3D car configurator with real-time color and trim customization. Built with Three.js, deployed on GitHub Pages.",
    tags: [
      { name: "Three.js", color: "blue-text-gradient" },
      { name: "HTML", color: "green-text-gradient" },
      { name: "JavaScript", color: "pink-text-gradient" },
    ],
    image: SHOT("https://0xwaya.github.io/dreamcar/"),
    image2: "https://0xwaya.github.io/dreamcar/",
    source_code_link: "https://github.com/0xwaya/dreamcar",
  },
];

export const projects1 = [
  {
    id: 0,
    title: "CEO Agent System",
    date: "Feb 2025 - Present",
    description:
      "16-agent LangGraph multi-agent AI: CEO/CTO/CFO + 6 domain directors + 7 execution specialists. Real-time SocketIO dashboard, artifact pipeline, and autonomous task execution. Live at wayalabs.com.",
    image: SHOT("https://wayalabs.com"),
    tags: ["LangGraph", "LangChain", "Python", "OpenAI", "Flask", "SocketIO", "Multi-Agent AI"],
    category: "ai agents",
    github: "https://github.com/0xwaya/ceo-agent-system",
    webapp: "https://wayalabs.com",
  },
  {
    id: 1,
    title: "QueenCity Soundboard",
    date: "2024 - Present",
    description:
      "Mobile-first event platform connecting Venezuelan artists and Midwest audiences. Next.js + Supabase + Ticket Tailor with full ticketing and RSVP flow.",
    image: queenCitySoundboardShot,
    tags: ["Next.js", "Supabase", "TypeScript", "TailwindCSS", "Ticket Tailor", "PostgreSQL"],
    category: "full stack",
    github: "https://github.com/0xwaya/queencity-soundboard",
    webapp: "https://queencitysoundboard.com",
  },
  {
    id: 2,
    title: "UrbanStone / Amazon Granite",
    date: "Apr 2025 - Present",
    description:
      "Rebrand site for Amazon Granite at urbanstone.co. Supplier scraper prototype for automated product catalog updates. Deployed via Vercel.",
    image: SHOT("https://urbanstone.co"),
    tags: ["Python", "Web Scraping", "Node.js", "React", "Vercel"],
    category: "full stack",
    github: "https://github.com/0xwaya/amazon-granite",
    webapp: "https://urbanstone.co",
  },
  {
    id: 3,
    title: "RadarTV",
    date: "2025 - Present",
    description:
      "Consolidating personal brand with media entity. Modern tech stack for high-performance streaming and community engagement.",
    image: SHOT("https://radartv.vercel.app"),
    tags: ["React", "Streaming", "Next.js", "TailwindCSS"],
    category: "full stack",
    github: "https://github.com/0xwaya/radartv",
    webapp: "https://radartv.vercel.app",
  },
  {
    id: 4,
    title: "Loro App / Pandemonium Squad NFT",
    date: "2022 - 2024",
    description:
      "Macaw NFT collection Dapp. Beta v0.1 testnet with trait-layer generation, rarity engine, and wallet-connected minting.",
    image: SHOT("https://loro.vercel.app"),
    tags: ["Solidity", "Hardhat", "React.js", "Ethers.js", "NFT", "Web3", "IPFS"],
    category: "web3",
    github: "https://github.com/0xwaya/loro-app",
    webapp: "https://loro.vercel.app",
  },
  {
    id: 5,
    title: "DreamCar",
    date: "2024",
    description:
      "Interactive 3D car configurator with real-time color and trim customization. Built with Three.js, deployed on GitHub Pages.",
    image: SHOT("https://0xwaya.github.io/dreamcar/"),
    tags: ["Three.js", "HTML", "CSS", "JavaScript"],
    category: "full stack",
    github: "https://github.com/0xwaya/dreamcar",
    webapp: "https://0xwaya.github.io/dreamcar/",
  },
  {
    id: 6,
    title: "DevRel Resources Hub",
    date: "2022 - 2023",
    description:
      "Collaborative open-source hub for Developer Relations resources, tools, and community links. Built for the DevRel Uni community.",
    image: devrelResourcesHubShot,
    tags: ["Next.js", "Open Source", "Developer Relations", "Community"],
    category: "full stack",
    github: "https://github.com/0xwaya/devreluni_rss",
    webapp: "https://dru-resources.vercel.app",
  },
  {
    id: 7,
    title: "wayalabs.vercel.app",
    date: "2024 - Present",
    description:
      "Early wayalabs site deployed on Vercel. Personal lab for AI experiments and prototype deployments.",
    image: SHOT("https://wayalabs.vercel.app"),
    tags: ["React", "Vercel", "AI", "Lab"],
    category: "ai agents",
    github: "https://github.com/0xwaya/wayalabs",
    webapp: "https://wayalabs.vercel.app",
  },
];

export { technologies, testimonials, experiences };
