import {
  certificate1,
  certDevrel,
  certSolidity,
  certWebdev,
  certCampbuidl,
  certCcip,
  certChainlinkFunctions,
  filecoin,
  hardhat,
  langchain,
  langgraph,
} from "../assets";
import {
  SiCss3,
  SiDocker,
  SiExpress,
  SiFigma,
  SiFlask,
  SiFramer,
  SiGit,
  SiHtml5,
  SiJavascript,
  SiMongodb,
  SiNodedotjs,
  SiNextdotjs,
  SiOpenai,
  SiPostgresql,
  SiPython,
  SiReact,
  SiRedis,
  SiRedux,
  SiSocketdotio,
  SiSolidity,
  SiSupabase,
  SiTailwindcss,
  SiThreedotjs,
  SiTypescript,
  SiVercel,
  SiVite,
  SiFastapi,
  SiEthereum,
  SiIpfs,
} from "react-icons/si/index.js";

const SHOT = (url) =>
  `https://image.thum.io/get/width/1280/crop/800/noanimate/${url}`;

export const navLinks = [
  { id: "project", title: "Projects" },
  { id: "experience", title: "Experience" },
  { id: "play", title: "Playground" },
];

const technologies = [
  { name: "Python", icon: SiPython },
  { name: "TypeScript", icon: SiTypescript },
  { name: "JavaScript", icon: SiJavascript },
  { name: "Solidity", icon: SiSolidity },
  { name: "HTML5", icon: SiHtml5 },
  { name: "CSS3", icon: SiCss3 },
  { name: "React", icon: SiReact },
  { name: "Next.js", icon: SiNextdotjs },
  { name: "Vite", icon: SiVite },
  { name: "Tailwind CSS", icon: SiTailwindcss },
  { name: "Framer Motion", icon: SiFramer },
  { name: "Redux", icon: SiRedux },
  { name: "Node.js", icon: SiNodedotjs },
  { name: "Express", icon: SiExpress },
  { name: "Flask", icon: SiFlask },
  { name: "FastAPI", icon: SiFastapi },
  { name: "OpenAI", icon: SiOpenai },
  { name: "Socket.IO", icon: SiSocketdotio },
  { name: "Ethereum", icon: SiEthereum },
  { name: "IPFS", icon: SiIpfs },
  { name: "Supabase", icon: SiSupabase },
  { name: "PostgreSQL", icon: SiPostgresql },
  { name: "MongoDB", icon: SiMongodb },
  { name: "Redis", icon: SiRedis },
  { name: "Docker", icon: SiDocker },
  { name: "Git", icon: SiGit },
  { name: "Vercel", icon: SiVercel },
  { name: "Figma", icon: SiFigma },
  { name: "Three.js", icon: SiThreedotjs },
  { name: "LangGraph", iconSrc: langgraph },
  { name: "LangChain", iconSrc: langchain },
  { name: "Ethers.js", icon: SiEthereum },
  { name: "Hardhat", iconSrc: hardhat },
  { name: "Filecoin", iconSrc: filecoin },
];

const experiences = [];

export const experiences1 = [
  {
    id: 0,
    img: "https://avatars.githubusercontent.com/u/136913552?v=4",
    role: "Founder & Lead AI Architect",
    company: "wayalabs · OpenClaw",
    date: "Jan 2025 – Present",
    desc: "Designed and deployed a fully autonomous AI agent system running natively on macOS. Built the LangGraph 16-agent CEO/CTO/CFO hierarchy with real-time SocketIO dashboard, artifact pipeline, and Telegram integration. Shipping OpenClaw — the open-source AI OS layer for autonomous agent orchestration.",
    skills: ["LangGraph", "LangChain", "Python", "OpenAI", "SocketIO", "Flask", "Autonomous Agents", "Multi-Agent AI"],
  },
  {
    id: 1,
    img: "https://opengraph.githubassets.com/1/0xwaya/queencity-soundboard",
    role: "Full-Stack Developer",
    company: "QueenCity Soundboard",
    date: "Sep 2023 – Present",
    desc: "Built a mobile-first event discovery platform bridging Venezuelan artists with Midwest audiences. Full-stack Next.js 14 + Supabase + Ticket Tailor integration, deployed at queencitysoundboard.com. Handles event listings, ticketing, and artist profiles.",
    skills: ["Next.js", "Supabase", "TypeScript", "TailwindCSS", "PostgreSQL", "Vercel"],
  },
  {
    id: 2,
    img: "https://opengraph.githubassets.com/1/0xwaya/loro-app",
    role: "Full-Stack Web3 Developer",
    company: "Pandemonium Squad · Loro App",
    date: "2022 – 2024",
    desc: "Led front-end and smart contract development for Pandemonium Squad NFT collection on Polygon. Built the Loro Dapp — NFT minting, trait-layer generation system, rarity engine, and wallet-connected UI. Deployed testnet v0.1 with Hardhat + Ethers.js.",
    skills: ["Solidity", "Hardhat", "React.js", "Ethers.js", "NFT", "Web3", "IPFS", "Polygon"],
  },
  {
    id: 3,
    img: "https://opengraph.githubassets.com/1/0xwaya/devreluni_rss",
    role: "Developer Relations · Open Source",
    company: "DevRel Uni · ETHDenver · ETHGlobal",
    date: "2022 – 2023",
    desc: "Graduated Camp BUIDL at ETHDenver — Solidity, DeFi, NFTs, and hackathon project delivery. Competed in ETHGlobal FVM Space Warp hackathon with a Filecoin-based project. Contributor to DevRel Uni resources hub and open-source Web3 tooling.",
    skills: ["Web3", "Open Source", "Solidity", "Filecoin", "Developer Relations", "Community"],
    doc: "https://github.com/0xwaya/bufficorn.bootcamp",
  },
  {
    id: 4,
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/IBM_logo.svg/200px-IBM_logo.svg.png",
    role: "Application Developer",
    company: "IBM",
    date: "2017 – 2021",
    desc: "Enterprise application development and systems integration at IBM. Worked on client-facing solutions across multiple business units, contributing to full lifecycle software delivery using agile methodologies.",
    skills: ["Java", "JavaScript", "Agile", "Systems Integration", "Enterprise Software"],
  },
];

const testimonials = [
  {
    project: "AI Agent Architecture",
    testimonial: "https://opengraph.githubassets.com/1/0xwaya/ceo-agent-system",
    name: "Edward Mercado",
    designation: "0xwaya - CEO Agent System",
    company: "16-agent LangGraph hierarchy with CEO/CTO/CFO layer, 6 domain directors, and 7 execution specialists.",
    image: "https://avatars.githubusercontent.com/u/136913552?v=4",
    source_code_link: "https://github.com/0xwaya/ceo-agent-system",
  },
  {
    project: "Web3 & NFT Development",
    testimonial: certificate1,
    name: "Edward Mercado",
    designation: "0xwaya - Loro Dapp / Pandemonium Squad",
    company: "Macaw NFT collection with trait-layer generation, rarity engine, wallet-connected minting on Polygon testnet.",
    image: "https://avatars.githubusercontent.com/u/136913552?v=4",
    source_code_link: "https://github.com/0xwaya/loro-app",
  },
];

export const certificates = [
  {
    project: "Chainlink CCIP",
    image: certCcip,
    name: "Chainlink",
    designation: "Cross-Chain Interoperability Protocol",
    company: "Certified in building cross-chain applications using Chainlink CCIP for secure token and message transfers.",
    source_code_link: "https://github.com/0xwaya",
  },
  {
    project: "Chainlink Functions",
    image: certChainlinkFunctions,
    name: "Chainlink",
    designation: "Chainlink Functions Developer",
    company: "Certified to build hybrid smart contracts using Chainlink Functions for off-chain compute and API access.",
    source_code_link: "https://github.com/0xwaya",
  },
  {
    project: "Camp BUIDL",
    image: certCampbuidl,
    name: "Bufficorn Ventures / ETHDenver",
    designation: "Web3 Bootcamp Graduate",
    company: "Completed ETHDenver Camp BUIDL: Solidity, DeFi, NFTs, and hackathon project delivery.",
    source_code_link: "https://github.com/0xwaya/bufficorn.bootcamp",
  },
  {
    project: "Solidity Development",
    image: certSolidity,
    name: "Alchemy University",
    designation: "Smart Contract Developer",
    company: "Certified in Solidity smart contract development: ERC standards, security patterns, and on-chain testing.",
    source_code_link: "https://github.com/0xwaya",
  },
  {
    project: "Developer Relations",
    image: certDevrel,
    name: "DevRel Uni",
    designation: "DevRel Certification",
    company: "Completed DevRel Uni program covering community building, technical writing, and developer advocacy.",
    source_code_link: "https://dru-resources.vercel.app",
  },
  {
    project: "Web Development",
    image: certWebdev,
    name: "freeCodeCamp",
    designation: "Full Stack Web Developer",
    company: "Certified in responsive web design, JavaScript algorithms, front-end libraries, and APIs.",
    source_code_link: "https://github.com/0xwaya",
  },
  {
    project: "Blockchain Fundamentals",
    image: certificate1,
    name: "Alchemy",
    designation: "Blockchain Developer",
    company: "Foundational certification in blockchain protocols, cryptography, consensus mechanisms, and Web3 tooling.",
    source_code_link: "https://github.com/0xwaya",
  },
];

export const projects = [
  {
    id: 0,
    name: "CEO Agent System",
    description:
      "16-agent LangGraph AI hierarchy with CEO/CTO/CFO layer, 6 domain directors, and 7 execution specialists. Real-time SocketIO dashboard, artifact pipeline, and autonomous task execution.",
    tags: [
      { name: "LangGraph", color: "blue-text-gradient" },
      { name: "Python", color: "green-text-gradient" },
      { name: "Multi-Agent AI", color: "pink-text-gradient" },
    ],
    image: SHOT("https://wayalabs.com"),
    image2: "https://wayalabs.com",
    source_code_link: "https://github.com/0xwaya/ceo-agent-system",
  },
  {
    id: 1,
    name: "QueenCity Soundboard",
    description:
      "Mobile-first event platform connecting Venezuelan artists with Midwest audiences. Next.js + Supabase + Ticket Tailor with full ticketing and RSVP flow.",
    tags: [
      { name: "Next.js", color: "blue-text-gradient" },
      { name: "Supabase", color: "green-text-gradient" },
      { name: "TypeScript", color: "pink-text-gradient" },
    ],
    image: SHOT("https://queencitysoundboard.com"),
    image2: "https://queencitysoundboard.com",
    source_code_link: "https://github.com/0xwaya/queencity-soundboard",
  },
  {
    id: 2,
    name: "UrbanStone / Amazon Granite",
    description:
      "Rebrand site for Amazon Granite at urbanstone.co. Supplier scraper prototype for automated product catalog updates. Deployed via Vercel.",
    tags: [
      { name: "React", color: "blue-text-gradient" },
      { name: "Python", color: "green-text-gradient" },
      { name: "Vercel", color: "pink-text-gradient" },
    ],
    image: SHOT("https://urbanstone.co"),
    image2: "https://urbanstone.co",
    source_code_link: "https://github.com/0xwaya/amazon-granite",
  },
  {
    id: 3,
    name: "RadarTV",
    description:
      "Consolidating personal brand with media entity. Modern tech stack for high-performance streaming and community engagement.",
    tags: [
      { name: "React", color: "blue-text-gradient" },
      { name: "Next.js", color: "green-text-gradient" },
      { name: "TailwindCSS", color: "pink-text-gradient" },
    ],
    image: SHOT("https://radartv.vercel.app"),
    image2: "https://radartv.vercel.app",
    source_code_link: "https://github.com/0xwaya/radartv",
  },
  {
    id: 4,
    name: "Loro App / Pandemonium Squad NFT",
    description:
      "Macaw NFT collection Dapp. Beta v0.1 testnet with trait-layer generation, rarity engine, and wallet-connected minting.",
    tags: [
      { name: "Solidity", color: "blue-text-gradient" },
      { name: "React.js", color: "green-text-gradient" },
      { name: "Ethers.js", color: "pink-text-gradient" },
    ],
    image: SHOT("https://loro.vercel.app"),
    image2: "https://loro.vercel.app",
    source_code_link: "https://github.com/0xwaya/loro-app",
  },
  {
    id: 5,
    name: "DreamCar",
    description:
      "Interactive 3D car configurator with real-time color and trim customization. Built with Three.js, deployed on GitHub Pages.",
    tags: [
      { name: "Three.js", color: "blue-text-gradient" },
      { name: "HTML", color: "green-text-gradient" },
      { name: "JavaScript", color: "pink-text-gradient" },
    ],
    image: SHOT("https://0xwaya.github.io/dreamcar/"),
    image2: "https://0xwaya.github.io/dreamcar/",
    source_code_link: "https://github.com/0xwaya/dreamcar",
  },
];

export const projects1 = [
  {
    id: 0,
    title: "CEO Agent System",
    date: "Feb 2025 - Present",
    description:
      "16-agent LangGraph multi-agent AI: CEO/CTO/CFO + 6 domain directors + 7 execution specialists. Real-time SocketIO dashboard, artifact pipeline, and autonomous task execution. Live at wayalabs.com.",
    image: SHOT("https://wayalabs.com"),
    tags: ["LangGraph", "LangChain", "Python", "OpenAI", "Flask", "SocketIO", "Multi-Agent AI"],
    category: "ai agents",
    github: "https://github.com/0xwaya/ceo-agent-system",
    webapp: "https://wayalabs.com",
  },
  {
    id: 1,
    title: "QueenCity Soundboard",
    date: "2024 - Present",
    description:
      "Mobile-first event platform connecting Venezuelan artists and Midwest audiences. Next.js + Supabase + Ticket Tailor with full ticketing and RSVP flow.",
    image: SHOT("https://queencitysoundboard.com"),
    tags: ["Next.js", "Supabase", "TypeScript", "TailwindCSS", "Ticket Tailor", "PostgreSQL"],
    category: "full stack",
    github: "https://github.com/0xwaya/queencity-soundboard",
    webapp: "https://queencitysoundboard.com",
  },
  {
    id: 2,
    title: "UrbanStone / Amazon Granite",
    date: "Apr 2025 - Present",
    description:
      "Rebrand site for Amazon Granite at urbanstone.co. Supplier scraper prototype for automated product catalog updates. Deployed via Vercel.",
    image: SHOT("https://urbanstone.co"),
    tags: ["Python", "Web Scraping", "Node.js", "React", "Vercel"],
    category: "full stack",
    github: "https://github.com/0xwaya/amazon-granite",
    webapp: "https://urbanstone.co",
  },
  {
    id: 3,
    title: "RadarTV",
    date: "2025 - Present",
    description:
      "Consolidating personal brand with media entity. Modern tech stack for high-performance streaming and community engagement.",
    image: SHOT("https://radartv.vercel.app"),
    tags: ["React", "Streaming", "Next.js", "TailwindCSS"],
    category: "full stack",
    github: "https://github.com/0xwaya/radartv",
    webapp: "https://radartv.vercel.app",
  },
  {
    id: 4,
    title: "Loro App / Pandemonium Squad NFT",
    date: "2022 - 2024",
    description:
      "Macaw NFT collection Dapp. Beta v0.1 testnet with trait-layer generation, rarity engine, and wallet-connected minting.",
    image: SHOT("https://loro.vercel.app"),
    tags: ["Solidity", "Hardhat", "React.js", "Ethers.js", "NFT", "Web3", "IPFS"],
    category: "web3",
    github: "https://github.com/0xwaya/loro-app",
    webapp: "https://loro.vercel.app",
  },
  {
    id: 5,
    title: "DreamCar",
    date: "2024",
    description:
      "Interactive 3D car configurator with real-time color and trim customization. Built with Three.js, deployed on GitHub Pages.",
    image: SHOT("https://0xwaya.github.io/dreamcar/"),
    tags: ["Three.js", "HTML", "CSS", "JavaScript"],
    category: "full stack",
    github: "https://github.com/0xwaya/dreamcar",
    webapp: "https://0xwaya.github.io/dreamcar/",
  },
  {
    id: 6,
    title: "DevRel Resources Hub",
    date: "2022 - 2023",
    description:
      "Collaborative open-source hub for Developer Relations resources, tools, and community links. Built for the DevRel Uni community.",
    image: SHOT("https://dru-resources.vercel.app"),
    tags: ["Next.js", "Open Source", "Developer Relations", "Community"],
    category: "full stack",
    github: "https://github.com/0xwaya/devreluni_rss",
    webapp: "https://dru-resources.vercel.app",
  },
  {
    id: 7,
    title: "wayalabs.vercel.app",
    date: "2024 - Present",
    description:
      "Early wayalabs site deployed on Vercel. Personal lab for AI experiments and prototype deployments.",
    image: SHOT("https://wayalabs.vercel.app"),
    tags: ["React", "Vercel", "AI", "Lab"],
    category: "ai agents",
    github: "https://github.com/0xwaya/wayalabs",
    webapp: "https://wayalabs.vercel.app",
  },
];

export { technologies, testimonials, experiences };
